[basic]
    # Required
    path = ".output/examples"
    exports = ["stills", "clip"]

    # Optional
    # min_width = 600
    # width = 0
    # max_width = 0
    # min_height = 400
    # height = 0
    # max_height = 0

    # font_name = "Hack Nerd Font"
    font_size = 20
    # style = "monokai"
    # indent_size = 4
    # line_spacing = 12
    # window_title = "main.py"
    max_line_display = 10
    max_width = 500
    # padding_horizontal = 40
    # padding_vertical = 40

    # window_ctl = true
    # window_title = ""
    fps = 10


[yt-code]
    path = "code-assets/"
    exports = ["stills", "clip"]
    font_size = 22
    line_spacing = 14
    max_line_dsiplay = 20
    max_width = 400
    # min_height = 400
    max_height = 800

[cmd-out-vertical-lg]
    path = "locomotes/"
    # path = "locomotes/"
    exports = ["clip"]
    font_size = 20
    max_line_display = 28
    width = 1000
    height = 900

[cmd-flex]
    path = "locomotes/"
    exports = ["gif"]
    font_size = 20


[cmd-out-1000x600]
    # path = ".output/examples"
    path = "locomotes/"
    exports = ["still"]
    font_size = 18
    max_line_display = 20
    width = 800
    # height = 600

[snippet-600]
    path = ".output/examples"
    exports = [ "clip"]
    font_size = 18
    width = 600