[raw]
    seq_start = ""
    seq_end = "from os import path"
    lang = "python3"

[file]
    seq_end_file = ".input/f_new.py"
    seq_start_file = ".input/f_old.py"
    lang = "python3"
    # seq_start_file = "my-file-original.py"

[diff]
    file = "my-file.py"
    rev = "3b468df..887bef8"
    lang = "python3"
    # repo = "."

[cmd]
    command = "fly apps list"
    logfile = "example.log"
    host_ctx = "donatas@fly ~"
    lang = "bash"

[basic]
    # Required
    path = ".output/examples"
    exports = ["stills", "clip"]

    # Optional
    min_width = 600
    # width = 0
    # max_width = 0
    min_height = 400
    # height = 0
    # max_height = 0

    # font_name = "Hack Nerd Font"
    font_size = 20
    # style = "lightbulb"
    indent_size = 4
    line_spacing = 12
    window_title = "main.py"
    max_line_display = 10
    # padding_horizontal = 40
    # padding_vertical = 40

    # window_ctl = true
    # window_title = ""
    fps = 10

