[my-file]
output.path = "examples/my-file"
file.dst = "my-file.py"
file.filename = "main.py"

[my-file-diff]
output.path = "examples/my-file-diff"
output.pil.font_size = 16
diff.file = "my-file.py"


[fly-apps-list]
output.path = "examples/fly-apps-list"
cmd.cmd = "fly apps list"
cmd.logfile = "example.log"
cmd.host_line = "donatas@fly ~"

